Add gcc to list of required apps
At least in Ubuntu 20.04, the install script errors out with the following code:

```
 building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/psutil
    gcc -pthread -B /opt/tljh/user/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/opt/tljh/user/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
    unable to execute 'gcc': No such file or directory
    C compiler or Python headers are not installed on this system. Try to run:
    sudo apt-get install gcc python3-dev
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/opt/tljh/user/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-o8krtv6q/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4vfz78g1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-o8krtv6q/psutil/
```
Simply adding gcc to the apt install list fixes this error, thus resulting in an easier install for most!